# Часть 1

In [ ]:
import numpy as np
import pandas as pd
pd.set_option('display.max.columns', 100)
# to draw pictures in jupyter notebook
%matplotlib inline 
import matplotlib.pyplot as plt
import seaborn as sns
# we don't like warnings
# you can comment the following 2 lines if you'd like to
import warnings
warnings.filterwarnings('ignore')
import io
import requests

In [6]:
data = pd.read_csv('C:/Users/kotsi/Downloads/adult.data.csv')
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

### 1. How many men and women (sex feature) are represented in this dataset?

In [7]:
data['sex'].value_counts()

Male      21790
Female    10771
Name: sex, dtype: int64

### 2. What is the average age (age feature) of women?

In [8]:
data.loc[data['sex'] == 'Female', 'age'].mean()#как бы по пересечению строки и столбца смотрим

36.85823043357163

### 3. What is the proportion of German citizens (native-country feature)?

In [9]:
float((data['native-country'] == 'Germany').sum()) / data.shape[0]

0.004207487485028101

### 4-5. What are mean value and standard deviation of the age of those who recieve more than 50K per year (salary feature) and those who receive less than 50K per year?

In [11]:
ages1 = data.loc[data['salary'] == '>50K', 'age']
ages2 = data.loc[data['salary'] == '<=50K', 'age']
print("The average age of the rich: {0} +- {1} years, poor - {2} +- {3} years.".format(
    round(ages1.mean()), round(ages1.std(), 1),
    round(ages2.mean()), round(ages2.std(), 1)))

The average age of the rich: 44 +- 10.5 years, poor - 37 +- 14.0 years.

### 6. Is it true that people who receive more than 50k have at least high school education? (education - Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate feature)

In [12]:
data.loc[data['salary'] == '>50K', 'education'].unique() # No

array(['HS-grad', 'Masters', 'Bachelors', 'Some-college', 'Assoc-voc',
       'Doctorate', 'Prof-school', 'Assoc-acdm', '7th-8th', '12th',
       '10th', '11th', '9th', '5th-6th', '1st-4th'], dtype=object)

### 7. Display statistics of age for each race (race feature) and each gender. Use groupby() and describe(). Find the maximum age of men of Amer-Indian-Eskimo race.

In [14]:
for (race, sex) in data.groupby(['race', 'sex']):
    print("Race: {0}, sex: {1}".format(race, sex))
    #print(sub_df['age'].describe())

Race: ('Amer-Indian-Eskimo', 'Female'), sex:        age         workclass  fnlwgt     education  education-num  \
212     35           Private  153790  Some-college             10
226     60                 ?   24215          10th              6
516     25           Private  267044  Some-college             10
596     23                 ?   99399  Some-college             10
940     31           Private   78602    Assoc-acdm             12
1715    39           Private   19914  Some-college             10
2036    19                 ?   33487  Some-college             10
2313    31         Local-gov  151726    Assoc-acdm             12
2383    63           Private   30602       7th-8th              4
2610    18           Private   40829          11th              7
2720    40         Local-gov   50442  Some-college             10
2993    29           Private  100405          10th              6
3589    31         Local-gov   50442  Some-college             10
3598    25         Local-gov   44216       HS-grad              9
3605    17           Private  130125          10th              6
3729    28         Local-gov   25864       HS-grad              9
3821    31           Private  395170     Assoc-voc             11
4112    38         State-gov   31352  Some-college             10
4169    27                 ?  129661     Assoc-voc             11
4348    40           Private   20109  Some-college             10
4948    60       Federal-gov   21876  Some-college             10
5127    55         State-gov   26290     Assoc-voc             11
5214    63                 ?  445168     Bachelors             13
5464    47           Private  184005       HS-grad              9
5481    19  Self-emp-not-inc   30800          10th              6
5624    21           Private  216070    Assoc-acdm             12
5775    37           Private  163199  Some-college             10
5846    33           Private  110998       HS-grad              9
6228    24           Private  336088       HS-grad              9
6391    41         State-gov   47170     Bachelors             13
...    ...               ...     ...           ...            ...
23237   47                 ?   89806  Some-college             10
23238   39           Private  106183       HS-grad              9
23724   31           Private  264864       HS-grad              9
24326   27         Local-gov   66824     Bachelors             13
24376   22           Private  233955     Bachelors             13
24402   30         Local-gov   99502     Assoc-voc             11
25016   30           Private  299223  Some-college             10
25047   47           Private  104068       HS-grad              9
25070   59           Private  205949       HS-grad              9
25125   61         State-gov  130466       HS-grad              9
25168   21           Private   75763  Some-college             10
26043   42           Private  134220     Assoc-voc             11
26243   50       Federal-gov   32801     Bachelors             13
26901   42           Private   86185  Some-college             10
27496   19           Private  243941  Some-college             10
27623   25           Private   25386     Assoc-voc             11
27657   48                 ?   61985           9th              5
28248   46         Local-gov  197988       1st-4th              2
28648   46       Federal-gov  199725     Assoc-voc             11
28785   50           Private  150975       HS-grad              9
28973   46         State-gov  363875  Some-college             10
29021   28           Private   25684       HS-grad              9
29408   36           Private   68089       HS-grad              9
29990   33           Private   31449    Assoc-acdm             12
30115   46      Self-emp-inc  320124       HS-grad              9
30586   42         Local-gov   29075    Assoc-acdm             12
30591   21           Private  164991       HS-grad              9
30782   28       Federal-gov   24153          10th              6
31087   30           Private   67187       HS-grad              9
32425   23           Private  180771       1st-4th              2

              marital-status         occupation    relationship  \
212            Never-married              Sales   Not-in-family
226                 Divorced                  ?   Not-in-family
516            Never-married       Adm-clerical   Not-in-family
596            Never-married                  ?       Unmarried
940                 Divorced      Other-service       Unmarried
1715                Divorced       Adm-clerical       Unmarried
2036           Never-married                  ?  Other-relative
2313           Never-married       Adm-clerical       Own-child
2383   Married-spouse-absent      Other-service       Unmarried
2610           Never-married              Sales  Other-relative
2720           Never-married       Adm-clerical       Unmarried
2993      Married-civ-spouse    Farming-fishing            Wife
3589           Never-married    Exec-managerial       Own-child
3598                Divorced       Adm-clerical   Not-in-family
3605           Never-married      Other-service       Own-child
3729           Never-married    Exec-managerial       Unmarried
3821      Married-civ-spouse      Other-service            Wife
4112                Divorced    Protective-serv       Unmarried
4169      Married-civ-spouse                  ?            Wife
4348                Divorced  Handlers-cleaners   Not-in-family
4948                Divorced     Prof-specialty   Not-in-family
5127                 Widowed    Exec-managerial   Not-in-family
5214                 Widowed                  ?   Not-in-family
5464                Divorced    Exec-managerial   Not-in-family
5481   Married-spouse-absent       Adm-clerical       Unmarried
5624      Married-civ-spouse       Adm-clerical            Wife
5775                Divorced       Tech-support   Not-in-family
5846           Never-married      Other-service  Other-relative
6228                Divorced    Exec-managerial   Not-in-family
6391      Married-civ-spouse     Prof-specialty            Wife
...                      ...                ...             ...
23237               Divorced                  ?   Not-in-family
23238               Divorced      Other-service       Unmarried
23724     Married-civ-spouse  Machine-op-inspct            Wife
24326          Never-married     Prof-specialty   Not-in-family
24376          Never-married     Prof-specialty   Not-in-family
24402               Divorced    Protective-serv       Unmarried
25016               Divorced              Sales       Unmarried
25047               Divorced     Prof-specialty       Unmarried
25070              Separated       Craft-repair       Unmarried
25125                Widowed       Adm-clerical       Unmarried
25168     Married-civ-spouse              Sales            Wife
26043               Divorced    Exec-managerial       Own-child
26243     Married-civ-spouse    Exec-managerial            Wife
26901                Widowed    Exec-managerial   Not-in-family
27496          Never-married              Sales       Own-child
27623          Never-married      Other-service       Unmarried
27657              Separated                  ?   Not-in-family
28248          Never-married      Other-service   Not-in-family
28648               Divorced       Craft-repair   Not-in-family
28785               Divorced  Machine-op-inspct   Not-in-family
28973               Divorced    Protective-serv       Unmarried
29021          Never-married     Prof-specialty   Not-in-family
29408          Never-married  Machine-op-inspct       Unmarried
29990               Divorced  Machine-op-inspct       Unmarried
30115     Married-civ-spouse    Exec-managerial            Wife
30586     Married-civ-spouse     Prof-specialty            Wife
30591               Divorced              Sales       Unmarried
30782     Married-civ-spouse      Other-service            Wife
31087          Never-married  Handlers-cleaners       Own-child
32425     Married-civ-spouse  Machine-op-inspct            Wife

                     race     sex  capital-gain  capital-loss  hours-per-week  \
212    Amer-Indian-Eskimo  Female             0             0              40
226    Amer-Indian-Eskimo  Female             0             0              10
516    Amer-Indian-Eskimo  Female             0             0              20
596    Amer-Indian-Eskimo  Female             0             0              25
940    Amer-Indian-Eskimo  Female             0             0              40
1715   Amer-Indian-Eskimo  Female             0             0              40
2036   Amer-Indian-Eskimo  Female             0             0              40
2313   Amer-Indian-Eskimo  Female             0             0              40
2383   Amer-Indian-Eskimo  Female             0             0              40
2610   Amer-Indian-Eskimo  Female             0             0              25
2720   Amer-Indian-Eskimo  Female          2977             0              35
2993   Amer-Indian-Eskimo  Female             0             0              40
3589   Amer-Indian-Eskimo  Female             0             0              32
3598   Amer-Indian-Eskimo  Female             0             0              35
3605   Amer-Indian-Eskimo  Female          1055             0              20
3729   Amer-Indian-Eskimo  Female             0             0              35
3821   Amer-Indian-Eskimo  Female             0             0              24
4112   Amer-Indian-Eskimo  Female             0             0              40
4169   Amer-Indian-Eskimo  Female             0             0              40
4348   Amer-Indian-Eskimo  Female             0             0              84
4948   Amer-Indian-Eskimo  Female             0             0              40
5127   Amer-Indian-Eskimo  Female             0             0              38
5214   Amer-Indian-Eskimo  Female             0             0              56
5464   Amer-Indian-Eskimo  Female          3325             0              45
5481   Amer-Indian-Eskimo  Female             0             0              40
5624   Amer-Indian-Eskimo  Female             0             0              46
5775   Amer-Indian-Eskimo  Female             0             0              40
5846   Amer-Indian-Eskimo  Female             0             0              36
6228   Amer-Indian-Eskimo  Female             0             0              50
6391   Amer-Indian-Eskimo  Female             0             0              48
...                   ...     ...           ...           ...             ...
23237  Amer-Indian-Eskimo  Female             0             0              35
23238  Amer-Indian-Eskimo  Female          6849             0              40
23724  Amer-Indian-Eskimo  Female             0             0              40
24326  Amer-Indian-Eskimo  Female          3325             0              43
24376  Amer-Indian-Eskimo  Female         14344             0              40
24402  Amer-Indian-Eskimo  Female             0             0              40
25016  Amer-Indian-Eskimo  Female             0             0              40
25047  Amer-Indian-Eskimo  Female             0             0              40
25070  Amer-Indian-Eskimo  Female             0             0              40
25125  Amer-Indian-Eskimo  Female             0             0              40
25168  Amer-Indian-Eskimo  Female             0             0              40
26043  Amer-Indian-Eskimo  Female             0             0              40
26243  Amer-Indian-Eskimo  Female             0             0              40
26901  Amer-Indian-Eskimo  Female             0             0              40
27496  Amer-Indian-Eskimo  Female             0          1721              25
27623  Amer-Indian-Eskimo  Female             0             0              40
27657  Amer-Indian-Eskimo  Female             0             0              20
28248  Amer-Indian-Eskimo  Female             0             0              20
28648  Amer-Indian-Eskimo  Female             0             0              60
28785  Amer-Indian-Eskimo  Female             0             0              40
28973  Amer-Indian-Eskimo  Female             0             0              40
29021  Amer-Indian-Eskimo  Female             0             0              40
29408  Amer-Indian-Eskimo  Female             0             0              40
29990  Amer-Indian-Eskimo  Female             0             0              40
30115  Amer-Indian-Eskimo  Female         15024             0              40
30586  Amer-Indian-Eskimo  Female             0             0              40
30591  Amer-Indian-Eskimo  Female             0             0              38
30782  Amer-Indian-Eskimo  Female             0             0              40
31087  Amer-Indian-Eskimo  Female             0             0               8
32425  Amer-Indian-Eskimo  Female             0             0              35

      native-country salary
212    United-States  <=50K
226    United-States  <=50K
516    United-States  <=50K
596    United-States  <=50K
940    United-States  <=50K
1715   United-States  <=50K
2036   United-States  <=50K
2313   United-States  <=50K
2383   United-States  <=50K
2610   United-States  <=50K
2720   United-States  <=50K
2993   United-States  <=50K
3589   United-States  <=50K
3598   United-States  <=50K
3605   United-States  <=50K
3729   United-States  <=50K
3821          Mexico  <=50K
4112   United-States   >50K
4169   United-States   >50K
4348   United-States  <=50K
4948   United-States  <=50K
5127   United-States  <=50K
5214   United-States  <=50K
5464   United-States  <=50K
5481   United-States  <=50K
5624   United-States   >50K
5775   United-States  <=50K
5846   United-States  <=50K
6228   United-States  <=50K
6391   United-States   >50K
...              ...    ...
23237  United-States  <=50K
23238  United-States  <=50K
23724  United-States  <=50K
24326  United-States  <=50K
24376  United-States   >50K
24402  United-States  <=50K
25016  United-States  <=50K
25047  United-States  <=50K
25070  United-States  <=50K
25125  United-States  <=50K
25168  United-States  <=50K
26043  United-States  <=50K
26243  United-States   >50K
26901  United-States  <=50K
27496  United-States  <=50K
27623  United-States  <=50K
27657  United-States  <=50K
28248  United-States  <=50K
28648  United-States  <=50K
28785  United-States  <=50K
28973  United-States  <=50K
29021  United-States  <=50K
29408  United-States  <=50K
29990  United-States  <=50K
30115  United-States   >50K
30586  United-States  <=50K
30591  United-States  <=50K
30782  United-States  <=50K
31087  United-States  <=50K
32425         Mexico  <=50K

[119 rows x 15 columns]
Race: ('Amer-Indian-Eskimo', 'Male'), sex:        age         workclass  fnlwgt     education  education-num  \
15      34           Private  245487       7th-8th              4
447     51           Private   56915       HS-grad              9
565     20           Private   27337       HS-grad              9
607     29           Private  182521       HS-grad              9
903     27                 ?   90270    Assoc-acdm             12
1216    48  Self-emp-not-inc  243631  Some-college             10
1425    46           Private  134727          11th              7
1464    40           Private  100584          10th              6
1494    27           Private   23940       HS-grad              9
1844    53           Private  121618       7th-8th              4
2401    20           Private  137651  Some-college             10
2445    31           Private  100997  Some-college             10
2488    52  Self-emp-not-inc  242341       7th-8th              4
2601    56       Federal-gov  162137       HS-grad              9
2622    42           Private  245626       HS-grad              9
2718    51           Private  209912     Bachelors             13
2798    35           Private   25955          11th              7
3406    31           Private  197023     Assoc-voc             11
3443    28           Private  259351          10th              6
3676    44           Private  100584       HS-grad              9
3707    41           Private  113555  Some-college             10
3838    45  Self-emp-not-inc  239093  Some-college             10
3843    20                 ?   34862  Some-college             10
4049    28           Private   25955     Assoc-voc             11
4287    43           Private  161226     Bachelors             13
4426    29           Private  120986       HS-grad              9
4611    41           Private  147314       HS-grad              9
4666    45           Private   26781       HS-grad              9
5022    42           Private  108506       HS-grad              9
5358    33           Private  163392       HS-grad              9
...    ...               ...     ...           ...            ...
27911   21           Private  245572           9th              5
27977   35           Private  197719  Some-college             10
28151   51  Self-emp-not-inc   78631  Some-college             10
28278   21           Private  304302       HS-grad              9
28297   29           Private   59732       HS-grad              9
28398   25           Private  258276  Some-college             10
28742   41           Private  118721          12th              8
28908   46           Private  176552          11th              7
29133   30           Private  356015          11th              7
29260   28           Private  314649  Some-college             10
29403   31           Private  112627       HS-grad              9
29537   46         Local-gov  133969       Masters             14
29864   40           Private  117917       HS-grad              9
30057   71  Self-emp-not-inc  322789       HS-grad              9
30382   34           Private  152246       HS-grad              9
30579   17           Private   27415          11th              7
30757   31                 ?   99483       HS-grad              9
30775   51         State-gov  243631          10th              6
30864   44         State-gov   98989     Bachelors             13
30938   43       Federal-gov  195385       HS-grad              9
30968   28           Private  124685  Some-college             10
30986   31         Local-gov   94991       HS-grad              9
30997   29           Private  107108  Some-college             10
31358   31       Federal-gov   59732       HS-grad              9
31915   38  Self-emp-not-inc  175732       HS-grad              9
32008   58                 ?   97969       1st-4th              2
32231   44           Private   33105       HS-grad              9
32242   33           Private  356015       HS-grad              9
32249   35           Private   91839     Bachelors             13
32551   32           Private   34066          10th              6

              marital-status         occupation    relationship  \
15        Married-civ-spouse   Transport-moving         Husband
447       Married-civ-spouse       Craft-repair         Husband
565            Never-married  Handlers-cleaners       Own-child
607            Never-married       Craft-repair   Not-in-family
903       Married-civ-spouse                  ?       Own-child
1216      Married-civ-spouse       Craft-repair         Husband
1425                Divorced  Machine-op-inspct       Unmarried
1464                Divorced       Craft-repair   Not-in-family
1494           Never-married  Handlers-cleaners  Other-relative
1844           Never-married   Transport-moving   Not-in-family
2401           Never-married  Machine-op-inspct       Own-child
2445      Married-civ-spouse     Prof-specialty         Husband
2488      Married-civ-spouse       Craft-repair         Husband
2601      Married-civ-spouse   Transport-moving         Husband
2622      Married-civ-spouse       Craft-repair         Husband
2718                Divorced    Exec-managerial   Not-in-family

In [17]:
#data.groupby(['race', 'sex']).aggregate(max)
for (race, sex), sub_df in data.groupby(['race', 'sex']):
    #где dub_df - набор строчек, соответствующих каждому подмножеству
    print("Race: {0}, sex: {1}".format(race, sex))
    print(sub_df['age'].describe())

Race: Amer-Indian-Eskimo, sex: Female
count    119.000000
mean      37.117647
std       13.114991
min       17.000000
25%       27.000000
50%       36.000000
75%       46.000000
max       80.000000
Name: age, dtype: float64
Race: Amer-Indian-Eskimo, sex: Male
count    192.000000
mean      37.208333
std       12.049563
min       17.000000
25%       28.000000
50%       35.000000
75%       45.000000
max       82.000000
Name: age, dtype: float64
Race: Asian-Pac-Islander, sex: Female
count    346.000000
mean      35.089595
std       12.300845
min       17.000000
25%       25.000000
50%       33.000000
75%       43.750000
max       75.000000
Name: age, dtype: float64
Race: Asian-Pac-Islander, sex: Male
count    693.000000
mean      39.073593
std       12.883944
min       18.000000
25%       29.000000
50%       37.000000
75%       46.000000
max       90.000000
Name: age, dtype: float64
Race: Black, sex: Female
count    1555.000000
mean       37.854019
std        12.637197
min        17.000000
25%        28.000000
50%        37.000000
75%        46.000000
max        90.000000
Name: age, dtype: float64
Race: Black, sex: Male
count    1569.000000
mean       37.682600
std        12.882612
min        17.000000
25%        27.000000
50%        36.000000
75%        46.000000
max        90.000000
Name: age, dtype: float64
Race: Other, sex: Female
count    109.000000
mean      31.678899
std       11.631599
min       17.000000
25%       23.000000
50%       29.000000
75%       39.000000
max       74.000000
Name: age, dtype: float64
Race: Other, sex: Male
count    162.000000
mean      34.654321
std       11.355531
min       17.000000
25%       26.000000
50%       32.000000
75%       42.000000
max       77.000000
Name: age, dtype: float64
Race: White, sex: Female
count    8642.000000
mean       36.811618
std        14.329093
min        17.000000
25%        25.000000
50%        35.000000
75%        46.000000
max        90.000000
Name: age, dtype: float64
Race: White, sex: Male
count    19174.000000
mean        39.652498
std         13.436029
min         17.000000
25%         29.000000
50%         38.000000
75%         49.000000
max         90.000000
Name: age, dtype: float64

### 8. Among whom the proportion of those who earn a lot(>50K) is more: among married or single men (marital-status feature)? Consider married those who have a marital-status starting with Married (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.

In [18]:
data.loc[(data['sex'] == 'Male') &
     (data['marital-status'].isin(['Never-married', 
                                   'Separated', 
                                   'Divorced',
                                   'Widowed'])), 'salary'].value_counts()

<=50K    7552
>50K      697
Name: salary, dtype: int64

In [19]:
data.loc[(data['sex'] == 'Male') &
     (data['marital-status'].str.startswith('Married')), 'salary'].value_counts()

<=50K    7576
>50K     5965
Name: salary, dtype: int64

In [20]:
data['marital-status'].value_counts()

Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: marital-status, dtype: int64

### 9. What is the maximum number of hours a person works per week (hours-per-week feature)? How many people work such a number of hours and what is the percentage of those who earn a lot among them?

In [21]:
max_load = data['hours-per-week'].max()
print("Max time - {0} hours./week.".format(max_load))

num_workaholics = data[data['hours-per-week'] == max_load].shape[0]
print("Total number of such hard workers {0}".format(num_workaholics))

rich_share = float(data[(data['hours-per-week'] == max_load)
                 & (data['salary'] == '>50K')].shape[0]) / num_workaholics
print("Percentage of rich among them {0}%".format(int(100 * rich_share)))

Max time - 99 hours./week.
Total number of such hard workers 85
Percentage of rich among them 29%

### 10. Count the average time of work (hours-per-week) those who earning a little and a lot (salary) for each country (native-country). What will these be for Japan?

In [22]:
for (country, salary), sub_df in data.groupby(['native-country', 'salary']):
    print(country, salary, round(sub_df['hours-per-week'].mean(), 2))

? <=50K 40.16
? >50K 45.55
Cambodia <=50K 41.42
Cambodia >50K 40.0
Canada <=50K 37.91
Canada >50K 45.64
China <=50K 37.38
China >50K 38.9
Columbia <=50K 38.68
Columbia >50K 50.0
Cuba <=50K 37.99
Cuba >50K 42.44
Dominican-Republic <=50K 42.34
Dominican-Republic >50K 47.0
Ecuador <=50K 38.04
Ecuador >50K 48.75
El-Salvador <=50K 36.03
El-Salvador >50K 45.0
England <=50K 40.48
England >50K 44.53
France <=50K 41.06
France >50K 50.75
Germany <=50K 39.14
Germany >50K 44.98
Greece <=50K 41.81
Greece >50K 50.62
Guatemala <=50K 39.36
Guatemala >50K 36.67
Haiti <=50K 36.33
Haiti >50K 42.75
Holand-Netherlands <=50K 40.0
Honduras <=50K 34.33
Honduras >50K 60.0
Hong <=50K 39.14
Hong >50K 45.0
Hungary <=50K 31.3
Hungary >50K 50.0
India <=50K 38.23
India >50K 46.48
Iran <=50K 41.44
Iran >50K 47.5
Ireland <=50K 40.95
Ireland >50K 48.0
Italy <=50K 39.62
Italy >50K 45.4
Jamaica <=50K 38.24
Jamaica >50K 41.1
Japan <=50K 41.0
Japan >50K 47.96
Laos <=50K 40.38
Laos >50K 40.0
Mexico <=50K 40.0
Mexico >50K 46.58
Nicaragua <=50K 36.09
Nicaragua >50K 37.5
Outlying-US(Guam-USVI-etc) <=50K 41.86
Peru <=50K 35.07
Peru >50K 40.0
Philippines <=50K 38.07
Philippines >50K 43.03
Poland <=50K 38.17
Poland >50K 39.0
Portugal <=50K 41.94
Portugal >50K 41.5
Puerto-Rico <=50K 38.47
Puerto-Rico >50K 39.42
Scotland <=50K 39.44
Scotland >50K 46.67
South <=50K 40.16
South >50K 51.44
Taiwan <=50K 33.77
Taiwan >50K 46.8
Thailand <=50K 42.87
Thailand >50K 58.33
Trinadad&Tobago <=50K 37.06
Trinadad&Tobago >50K 40.0
United-States <=50K 38.8
United-States >50K 45.51
Vietnam <=50K 37.19
Vietnam >50K 39.2
Yugoslavia <=50K 41.6
Yugoslavia >50K 49.5

In [37]:
for salary, sub in data.loc[data['native-country']=='Japan'].groupby('salary'):
    print("Hours-per-week: {}".format(sub['hours-per-week'].mean()))

Hours-per-week: 41.0
Hours-per-week: 47.958333333333336

### Или

In [23]:
pd.crosstab(data['native-country'], data['salary'], #метод crosstab - создает таблицу по cross join
           values=data['hours-per-week'], aggfunc=np.mean).T

native-country,?,Cambodia,Canada,China,Columbia,Cuba,Dominican-Republic,Ecuador,El-Salvador,England,France,Germany,Greece,Guatemala,Haiti,Holand-Netherlands,Honduras,Hong,Hungary,India,Iran,Ireland,Italy,Jamaica,Japan,Laos,Mexico,Nicaragua,Outlying-US(Guam-USVI-etc),Peru,Philippines,Poland,Portugal,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia
salary,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
<=50K,40.164760,41.416667,37.914634,37.381818,38.684211,37.985714,42.338235,38.041667,36.030928,40.483333,41.058824,39.139785,41.809524,39.360656,36.325,40.0,34.333333,39.142857,31.3,38.233333,41.44,40.947368,39.625,38.239437,41.000000,40.375,40.003279,36.09375,41.857143,35.068966,38.065693,38.166667,41.939394,38.470588,39.444444,40.15625,33.774194,42.866667,37.058824,38.799127,37.193548,41.6
>50K,45.547945,40.000000,45.641026,38.900000,50.000000,42.440000,47.000000,48.750000,45.000000,44.533333,50.750000,44.977273,50.625000,36.666667,42.750,NaN,60.000000,45.000000,50.0,46.475000,47.50,48.000000,45.400,41.100000,47.958333,40.000,46.575758,37.50000,NaN,40.000000,43.032787,39.000000,41.500000,39.416667,46.666667,51.43750,46.800000,58.333333,40.000000,45.505369,39.200000,49.5